Add download only mode

diff --git a/compilation/bootstrap-chroma b/compilation/bootstrap-chroma
--- a/compilation/bootstrap-chroma
+++ b/compilation/bootstrap-chroma
@@ -82,18 +82,6 @@ clone-if-needed() {
 
   if ! [[ -d "$dir" ]]; then
     case "$host" in
-      hazelhen)
-        cat<<EOF
-The git repository for “$dir” could not be found, it has to be cloned.
-Unfortunately outgoing HTTPS connections as needed for “git clone” are blocked
-by the firewall. You will have to download the repository yourself. Execute the
-following commands:
-
-    cd "$PWD"
-    git clone "$url" --recursive -b "$branch"
-    rm -f configure Makefile
-EOF
-        ;;
       *)
         git clone "$url" --recursive -b "$branch"
 
@@ -113,7 +101,7 @@ EOF
 # not invoked once it has correctly built.
 make-make-install() {
   if ! [[ -f build-succeeded ]]; then
-    nice make $make_smp_flags VERBOSE=1
+    nice make -j $_arg_make_j VERBOSE=1
     make install VERBOSE=1
     touch build-succeeded
     if [[ -d "$prefix/lib" ]]; then
@@ -178,7 +166,7 @@ die()
 begins_with_short_option()
 {
   local first_option all_short_options
-  all_short_options='hVmcjiqQpPsSC'
+  all_short_options='hVdmcjiqQpPsSC'
   first_option="${1:0:1}"
   test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -189,9 +177,10 @@ begins_with_short_option()
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_verbose=yes
+_arg_download_only=no
 _arg_autodetect_machine=yes
 _arg_compiler=
-_arg_make_j=
+_arg_make_j="$(nproc)"
 _arg_isa=
 _arg_only_qphix=no
 _arg_qphix_branch="devel"
@@ -240,13 +229,14 @@ After this script ran though, you will have the following directories::
     BASE/sources/qmp
     BASE/sources/qphix
 "
-  printf 'Usage: %s [-h|--help] [-V|--(no-)verbose] [-m|--(no-)autodetect-machine] [-c|--compiler <arg>] [-j|--make-j <arg>] [-i|--isa <arg>] [-q|--(no-)only-qphix] [-Q|--qphix-branch <arg>] [-p|--precision <arg>] [-P|--precision-inner <arg>] [-s|--soalen <arg>] [-S|--soalen-inner <arg>] [-C|--chroma-branch <arg>] <basedir>\n' "$0"
+  printf 'Usage: %s [-h|--help] [-V|--(no-)verbose] [-d|--(no-)download-only] [-m|--(no-)autodetect-machine] [-c|--compiler <arg>] [-j|--make-j <arg>] [-i|--isa <arg>] [-q|--(no-)only-qphix] [-Q|--qphix-branch <arg>] [-p|--precision <arg>] [-P|--precision-inner <arg>] [-s|--soalen <arg>] [-S|--soalen-inner <arg>] [-C|--chroma-branch <arg>] <basedir>\n' "$0"
   printf "\t%s\n" "<basedir>: Base path"
   printf "\t%s\n" "-h,--help: Prints help"
   printf "\t%s\n" "-V,--verbose,--no-verbose: Print Bash commands executed (yes by default)"
+  printf "\t%s\n" "-d,--download-only,--no-download-only: Download only (for systems like Hazel Hen) (no by default)"
   printf "\t%s\n" "-m,--autodetect-machine,--no-autodetect-machine: Automatically figure out which machine we are on (yes by default)"
   printf "\t%s\n" "-c,--compiler: Compiler family to use, defaults to best on given machine (no default)"
-  printf "\t%s\n" "-j,--make-j: Maximum number of parallel processes used by make (no default)"
+  printf "\t%s\n" "-j,--make-j: Maximum number of parallel processes used by make (default: '"$(nproc)"')"
   printf "\t%s\n" "-i,--isa: Manual instruction set architecture (ISA), usually automatically set (no default)"
   printf "\t%s\n" "-q,--only-qphix,--no-only-qphix: Only compile QPhiX, not Chroma (no by default)"
   printf "\t%s\n" "-Q,--qphix-branch: QPhiX git branch (default: '"devel"')"
@@ -281,6 +271,18 @@ parse_commandline ()
         if test -n "$_next" -a "$_next" != "$_key"
         then
           begins_with_short_option "$_next" && shift && set -- "-V" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -d|--no-download-only|--download-only)
+        _arg_download_only="on"
+        test "${1:0:5}" = "--no-" && _arg_download_only="off"
+        ;;
+      -d*)
+        _arg_download_only="on"
+        _next="${_key##-d}"
+        if test -n "$_next" -a "$_next" != "$_key"
+        then
+          begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
         fi
         ;;
       -m|--no-autodetect-machine|--autodetect-machine)
@@ -451,55 +453,126 @@ assign_positional_args
 # will give some feeling for the time it needs to compile.
 PS4='+[${SECONDS}s] '
 
-if [[ "$opt_verbose" = "true" ]]; then
+if [[ "$_arg_verbose" = "true" ]]; then
   set -x
 fi
 
 # Create the target directory and then store the absolute path to this
 # directory. Many compilation scripts have issues with linking to relative
 # paths.
-mkdir -p "$1"
-pushd "$1"
+mkdir -p "$_arg_basedir"
+pushd "$_arg_basedir"
 basedir="$PWD"
 popd
+
+# Directory where the git repositories reside.
+sourcedir="$basedir/sources"
+mkdir -p "$sourcedir"
 
 # Set all locale to C, such that compiler error messages are all in English.
 # This makes debugging way easier because you can search for the messages
 # online.
 export LC_ALL=C
 
+###############################################################################
+#                                  Download                                   #
+###############################################################################
+
+# Download is done as an early step. This allows users to download all the
+# needed files on a different machine as internet access is blocked on machines
+# like Hazel Hen.
+
+pushd "$sourcedir"
+
+# CMake
+url=https://cmake.org/files/v3.9/cmake-3.9.1.tar.gz
+if ! [[ -f "${url##*/}" ]]; then
+  wget "$url"
+fi
+if ! [[ -d "$repo" ]]; then
+  tar -xf "${url##*/}"
+  mv cmake-3.9.1 cmake
+fi
+
+# QMP
+clone-if-needed https://github.com/usqcd-software/qmp.git $repo master
+
+# libxml2
+clone-if-needed https://git.gnome.org/browse/libxml2 $repo v2.9.4
+
+# QDP++
+clone-if-needed https://github.com/usqcd-software/qdpxx.git $repo devel
+
+# QPhiX
+clone-if-needed https://github.com/JeffersonLab/qphix.git $repo "$_arg_qphix_branch"
+
+# GNU MP
+if ! [[ -d "$repo" ]];
+then
+  # The upstream website only has a download as an LZMA compressed file. The
+  # CentOS does not provide an `lzip` command. Also, there is no module
+  # available that would supply it. Building `lzip` from source seems like a
+  # waste of effort. Therefore I have just repacked that on my local machine
+  # and uploaded to my webspace.
+  url=http://bulk.martin-ueding.de/gmp-6.1.2.tar.gz
+  #url=https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz
+
+  wget "$url"
+  tar -xf "${url##*/}"
+  mv gmp-6.1.2 gmp
+fi
+
+# Chroma
+clone-if-needed https://github.com/JeffersonLab/chroma.git $repo "$_arg_chroma_branch"
+
+if [[ "$_arg_download_only" = "yes" ]]; then
+  set +x
+  echo "User wanted do download only, we are done here."
+  exit 0
+fi
+
+popd
+
+###############################################################################
+#                           Compiler Flag Selection                           #
+###############################################################################
+
 # Determine the fully qualified hostname and then set the optimal default
 # compiler for the architecture found.
 hostname_f="$(hostname -f)"
-if [[ "${opt_machine}" == "local" ]]; then
-  if [[ -z "${opt_isa}" ]]; then
+
+if [[ "$_arg_autodetect_machine" = "no" ]]; then
+  if [[ -z "$_arg_isa" ]]; then
     echo "Builds on local machines require the -i option to be passed (ISA: avx, avx2, avx512)"
     exit 1
   fi
   host=local
-  isa=${opt_isa}
-  compiler="${opt_compiler-gcc}"
-elif [[ "$hostname_f" =~ [^.]*\.hww\.de ]]; then
-  host=hazelhen
-  isa=avx2
-  compiler="${opt_compiler-icc}"
-elif [[ "$hostname_f" =~ [^.]*\.jureca ]]; then
-  host=jureca
-  isa=avx2
-  compiler="${opt_compiler-icc}"
-elif [[ "$hostname_f" =~ [^.]*\.marconi.cineca.it ]]; then
-  if [[ -n "${ENV_KNL_HOME-}" ]]; then
-    host=marconi-a2
-    isa=avx512
-    compiler="${opt_compiler-icc}"
+  isa=$_arg_isa
+  compiler="${_arg_compiler-gcc}"
+else
+  if [[ "$hostname_f" =~ eslogin[0-9]+ ]]; then
+    host=hazelhen
+    isa=avx2
+    compiler="${_arg_compiler-icc}"
+  elif [[ "$hostname_f" =~ [^.]*\.jureca ]]; then
+    host=jureca
+    isa=avx2
+    compiler="${_arg_compiler-icc}"
+  elif [[ "$hostname_f" =~ [^.]*\.marconi.cineca.it ]]; then
+    if [[ -n "${ENV_KNL_HOME-}" ]]; then
+      host=marconi-a2
+      isa=avx512
+      compiler="${_arg_compiler-icc}"
+    else
+      set +x
+      echo 'You seem to be running on Marconi but the environment variable ENV_KNL_HOME is not set. This script currently only supports Marconi A2, so please do `module load env-knl` to select the KNL partition.'
+      exit 1
+    fi
   else
-    echo 'You seem to be running on Marconi but the environment variable ENV_KNL_HOME is not set. This script currently only supports Marconi A2, so please do `module load env-knl` to select the KNL partition.'
+    set +x
+    echo "This machine is neither explicitly a 'local' machine nor JURECA nor Hazel Hen nor Marconi A2. It is not clear what should be done, please update the script."
     exit 1
   fi
-else
-  set +x
-  echo "This machine is neither explicitly a 'local' machine nor JURECA nor Hazel Hen nor Marconi A2. It is not clear what should be done, please update the script."
-  exit 1
 fi
 
 # Set up the chosen compiler.
@@ -618,10 +691,6 @@ case "$compiler" in
     ;;
 esac
 
-# Directory where the git repositories reside.
-sourcedir="$basedir/sources"
-mkdir -p "$sourcedir"
-
 # Directory for the installed files (headers, libraries, executables). This
 # contains the chosen compiler in the dirname such that multiple compilers can
 # be used simultaneously.
@@ -686,16 +755,6 @@ print-fancy-heading $repo
 
 case "$host" in
   hazelhen)
-    # Download CMake and unpack it.
-    url=https://cmake.org/files/v3.9/cmake-3.9.1.tar.gz
-    if ! [[ -f "${url##*/}" ]]; then
-      wget "$url"
-    fi
-    if ! [[ -d "$repo" ]]; then
-      tar -xf "${url##*/}"
-      mv cmake-3.9.1 cmake
-    fi
-
     pushd "$repo"
     if ! [[ -f Makefile ]]; then
       ./bootstrap --prefix="$prefix"
@@ -711,7 +770,6 @@ esac
 
 repo=qmp
 print-fancy-heading $repo
-clone-if-needed https://github.com/usqcd-software/qmp.git $repo master
 
 cflags="$base_cflags $openmp_flags"
 cxxflags="$base_cxxflags $openmp_flags"
@@ -738,7 +796,6 @@ case "$host" in
   jureca|marconi-a2)
     repo=libxml2
     print-fancy-heading $repo
-    clone-if-needed https://git.gnome.org/browse/libxml2 $repo v2.9.4
 
     cflags="$base_cflags"
     cxxflags="$base_cxxflags"
@@ -795,7 +852,6 @@ esac
 
 repo=qdpxx
 print-fancy-heading $repo
-clone-if-needed https://github.com/usqcd-software/qdpxx.git $repo devel
 
 cflags="$base_cflags $openmp_flags"
 cxxflags="$base_cxxflags $openmp_flags $cxx11_flags"
@@ -812,7 +868,7 @@ if ! [[ -f Makefile ]]; then
     --enable-sse --enable-sse2 \
     --enable-parallel-arch=parscalar \
     --enable-parallel-io \
-    --enable-precision=$opt_precision \
+    --enable-precision=$_arg_precision \
     --with-libxml2="$libxml" \
     --with-qmp="$prefix" \
     CFLAGS="$cflags" CXXFLAGS="$cxxflags"
@@ -826,7 +882,6 @@ popd
 
 repo=qphix
 print-fancy-heading $repo
-clone-if-needed https://github.com/JeffersonLab/qphix.git $repo "$opt_qphix_branch"
 
 case $host in
   jureca)
@@ -892,7 +947,7 @@ fi
 make-make-install
 popd
 
-if [[ "$opt_only_qphix" = "true" ]]; then
+if [[ "$_arg_only_qphix" = "true" ]]; then
   echo "QPhiX is installed, user wished to abort here."
   exit 0
 fi
@@ -931,20 +986,6 @@ case "$host" in
     repo=gmp
     print-fancy-heading $repo
 
-    if ! [[ -d "$repo" ]];
-    then
-      # The upstream website only has a download as an LZMA compressed file. The
-      # CentOS does not provide an `lzip` command. Also, there is no module
-      # available that would supply it. Building `lzip` from source seems like a
-      # waste of effort. Therefore I have just repacked that on my local machine
-      # and uploaded to my webspace.
-      url=http://bulk.martin-ueding.de/gmp-6.1.2.tar.gz
-      #url=https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz
-
-      wget "$url"
-      tar -xf "${url##*/}"
-      mv gmp-6.1.2 gmp
-    fi
 
     cflags="$base_cflags"
     cxxflags="$base_cxxflags"
@@ -972,7 +1013,6 @@ esac
 
 repo=chroma
 print-fancy-heading $repo
-clone-if-needed https://github.com/JeffersonLab/chroma.git $repo "$opt_chroma_branch"
 
 cflags="$base_cflags $openmp_flags"
 cxxflags="$base_cxxflags $openmp_flags"
@@ -994,8 +1034,8 @@ case "$host" in
 esac
 
 # Overwrite with the value that the user has chosen, if it is set.
-soalen=${opt_soalen-$soalen}
-inner_soalen=${opt_inner_soalen-$inner_soalen}
+soalen=${_arg_soalen-$soalen}
+inner_soalen=${_arg_soalen_inner-$inner_soalen}
 
 mkdir -p "$build/$repo"
 pushd "$build/$repo"
@@ -1004,7 +1044,7 @@ if ! [[ -f Makefile ]]; then
     --enable-openmp \
     --enable-parallel-arch=parscalar \
     --enable-parallel-io \
-    --enable-precision=$opt_precision \
+    --enable-precision=$_arg_precision \
     --enable-qdp-alignment=128 \
     --enable-sse2 \
     --with-gmp="$gmp" \
@@ -1015,7 +1055,7 @@ if ! [[ -f Makefile ]]; then
     --enable-qphix-solver-arch=$isa \
     --enable-qphix-solver-soalen=$soalen \
     --enable-qphix-solver-inner-soalen=$inner_soalen \
-    --enable-qphix-solver-inner-type=$opt_inner_precision \
+    --enable-qphix-solver-inner-type=$_arg_precision_inner \
     CFLAGS="$cflags" CXXFLAGS="$cxxflags"
 fi
 make-make-install
